<a href="https://colab.research.google.com/github/jacob7123/TensorFlow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, I am going to cover some of the most fumdamental comcepts of tensors using Tensorflow.

More specifically, I am going to cover:
* Introduction to tensor
* Getting information from tensor
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function(a way to speed up my regular Python function)
* Using GPUs with Tensorflow(or TPUs)
* Exercises to try myself


## Introduction to tensor

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.14.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of the dimensions of tensor(ndim stands for number of dimension)
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
#Create matrix(Has more than 1 dimension)
matrix = tf.constant([[10, 7],
            [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Create another matrix
another_matrix = tf.constant([[10., 7.],
                [3., 2.],
                [8., 9.]], dtype = tf.float16) #Specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#Lets create a tensor
tensor = tf.constant([[[1, 2, 3],
            [4, 5, 6]],
            [[7, 8, 9],
             [10, 11, 12]],
            [[13, 14, 15],
             [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we have create so far:

* Scalar: a single number
* Vector: a number with direection(e.g. wind speed and direction)
* Matrix: a 2-dimension array of number
* Tensor: an n-dimensional array of number(n can be any number, a 0-dimensional tensor is a sclar, a 1-dimensional tensor is a vecotr)

###Create tensor with `tf.Variable`


In [ ]:
#Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
 #Let's tey one of the elements in our changeable tensor
 changeable_tensor[0] = 7
 changeable_tensor


TypeError: ignored

In [ ]:
#How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#Let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

🔑**Note** Rarely in practice will you need to decide whether to use `th.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you. Howevere, if in doubt, use `tf,constant` and change it later if needed.

###Create random tensors
Random tensors are tensor of some abitrary size which contain random numbers.

In [ ]:
#Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) #Set seed for reproducibility
random_1 = random_1.normal(shape = (3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape = (3, 2))
#Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###Shuffle the order of elements in a tensor

In [ ]:
#Shuffle a tensor(valuable for when you want to shuffle your data so the inherent order does not effect learning)
not_shuffled = tf.constant([[10, 7],
               [3, 4],
               [2, 5]])

#Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
#Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

#Exercise: shuffle

##1

In [ ]:
not_shuffled = tf.constant([[100, 70],
               [30, 40],
               [20, 50]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 30,  40],
       [ 20,  50],
       [100,  70]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40],
       [ 20,  50]], dtype=int32)>

##2

In [ ]:
not_shuffled = tf.constant([[110, 17],
               [13, 14],
               [12, 15]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 12,  15],
       [ 13,  14],
       [110,  17]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[110,  17],
       [ 13,  14],
       [ 12,  15]], dtype=int32)>

##3

In [ ]:
not_shuffled = tf.constant([[210, 27],
               [23, 24],
               [22, 25]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[210,  27],
       [ 22,  25],
       [ 23,  24]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

##4

In [ ]:
not_shuffled = tf.constant([[102, 72],
               [32, 42],
               [22, 52]])

##5

In [ ]:
not_shuffled = tf.constant([[1044, 744],
               [344, 444],
               [244, 544]])