<a href="https://colab.research.google.com/github/jacob7123/TensorFlow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, I am going to cover some of the most fumdamental comcepts of tensors using Tensorflow.

More specifically, I am going to cover:
* Introduction to tensor
* Getting information from tensor
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function(a way to speed up my regular Python function)
* Using GPUs with Tensorflow(or TPUs)
* Exercises to try myself


## Introduction to tensor

In [1]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.14.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of the dimensions of tensor(ndim stands for number of dimension)
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector
vector.ndim

1

In [6]:
#Create matrix(Has more than 1 dimension)
matrix = tf.constant([[10, 7],
            [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
#Create another matrix
another_matrix = tf.constant([[10., 7.],
                [3., 2.],
                [8., 9.]], dtype = tf.float16) #Specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
#Lets create a tensor
tensor = tf.constant([[[1, 2, 3],
            [4, 5, 6]],
            [[7, 8, 9],
             [10, 11, 12]],
            [[13, 14, 15],
             [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we have create so far:

* Scalar: a single number
* Vector: a number with direection(e.g. wind speed and direction)
* Matrix: a 2-dimension array of number
* Tensor: an n-dimensional array of number(n can be any number, a 0-dimensional tensor is a sclar, a 1-dimensional tensor is a vecotr)

###Create tensor with `tf.Variable`


In [14]:
#Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
 #Let's tey one of the elements in our changeable tensor
 changeable_tensor[0] = 7
 changeable_tensor


TypeError: ignored

In [18]:
#How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
#Let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

🔑**Note** Rarely in practice will you need to decide whether to use `th.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you. Howevere, if in doubt, use `tf,constant` and change it later if needed.

###Create random tensors
Random tensors are tensor of some abitrary size which contain random numbers.

In [19]:
#Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) #Set seed for reproducibility
random_1 = random_1.normal(shape = (3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape = (3, 2))
#Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###Shuffle the order of elements in a tensor

In [20]:
#Shuffle a tensor(valuable for when you want to shuffle your data so the inherent order does not effect learning)
not_shuffled = tf.constant([[10, 7],
               [3, 4],
               [2, 5]])

#Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [21]:
#Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

#Exercise: shuffle
Read this : https://www.tensorflow.org/api_docs/python/tf/random/set_seed

It looks like if we want our shuffled tensors to be in the same order, we have got to use global level random seed as well as the operation level random seed:
##Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

##1

In [22]:
not_shuffled = tf.constant([[100, 70],
               [30, 40],
               [20, 50]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 30,  40],
       [ 20,  50],
       [100,  70]], dtype=int32)>

In [23]:
tf.random.set_seed(42) #Global level random seed
tf.random.shuffle(not_shuffled, seed = 42) #operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40],
       [ 20,  50]], dtype=int32)>

##2

In [24]:
not_shuffled = tf.constant([[110, 17],
               [13, 14],
               [12, 15]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 13,  14],
       [ 12,  15],
       [110,  17]], dtype=int32)>

In [25]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[110,  17],
       [ 13,  14],
       [ 12,  15]], dtype=int32)>

##3

In [26]:
not_shuffled = tf.constant([[210, 27],
               [23, 24],
               [22, 25]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 23,  24],
       [ 22,  25],
       [210,  27]], dtype=int32)>

In [27]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[210,  27],
       [ 23,  24],
       [ 22,  25]], dtype=int32)>

###Other ways to make tensors


In [28]:
#Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [29]:
#Create a tensor of all zeros
tf.zeros(shape = (3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

###Tuen NumPy arrays into tensors

The main defferent between NumPy array and TensorFlow tensors is that tensors can be run on GPU(much faster for numerical computing)

In [30]:
#You can also turn NumPy arrays into tensor
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32) #create a NumPy array between 1 to 25
numpy_A
# x = tf.constant(some_matrix) #capital for matrix or tensor
# y = tf.constant(vector) #non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [31]:
A = tf.constant(numpy_A, shape = (2, 3, 4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

###Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size  

In [32]:
#Create a rank4 tensor(4 dimensions)
rank_4_tensor = tf.zeros(shape = [2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [33]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [34]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [35]:
#Get various attributes of our tensor
print("Datatype of every elements: ", rank_4_tensor.dtype)
print("Number of dimension: ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axies: ", rank_4_tensor.shape[0])
print("Elements along the last axies: ", rank_4_tensor.shape[-1])
print("Total number of elements on our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements on our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every elements:  <dtype: 'float32'>
Number of dimension:  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axies:  2
Elements along the last axies:  5
Total number of elements on our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements on our tensor:  120


###Indexing tensors

Tensors can be indexed just like Python lists.

In [37]:
some_list = [1, 2, 3, 4, 5]
some_list[:2]

[1, 2]

In [38]:
#Get the first 2 elements of each dimision
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [39]:
some_list[:1]

[1]

In [43]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [46]:
#Get the first element from each dimension from each index expect for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [48]:
#Create a rank 2 tensor(2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [49]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [50]:
some_list, some_list[-1]

([1, 2, 3, 4, 5], 5)

In [61]:
#Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [62]:
#Adding extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # same as rank_2_tensor[:, :, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [64]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) #"-1" neams expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [67]:
#Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis = 0) # expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [68]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

###Manipilating tensors(tensor operations)

**Basic operation**

`+`,`-`,`*`,`/`

In [75]:
#You can add value to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [76]:
#Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [77]:
#Multiplication also work
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [79]:
#Substraction if you want
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [80]:
#We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>