<a href="https://colab.research.google.com/github/jacob7123/TensorFlow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, I am going to cover some of the most fumdamental comcepts of tensors using Tensorflow.

More specifically, I am going to cover:
* Introduction to tensor
* Getting information from tensor
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function(a way to speed up my regular Python function)
* Using GPUs with Tensorflow(or TPUs)
* Exercises to try myself


## Introduction to tensor

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.14.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of the dimensions of tensor(ndim stands for number of dimension)
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
#Create matrix(Has more than 1 dimension)
matrix = tf.constant([[10, 7],
            [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Create another matrix
another_matrix = tf.constant([[10., 7.],
                [3., 2.],
                [8., 9.]], dtype = tf.float16) #Specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#Lets create a tensor
tensor = tf.constant([[[1, 2, 3],
            [4, 5, 6]],
            [[7, 8, 9],
             [10, 11, 12]],
            [[13, 14, 15],
             [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we have create so far:

* Scalar: a single number
* Vector: a number with direection(e.g. wind speed and direction)
* Matrix: a 2-dimension array of number
* Tensor: an n-dimensional array of number(n can be any number, a 0-dimensional tensor is a sclar, a 1-dimensional tensor is a vecotr)

###Create tensor with `tf.Variable`


In [ ]:
#Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#Let's tey one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor


TypeError: ignored

In [ ]:
#How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#Let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

🔑**Note** Rarely in practice will you need to decide whether to use `th.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you. Howevere, if in doubt, use `tf,constant` and change it later if needed.

###Create random tensors
Random tensors are tensor of some abitrary size which contain random numbers.

In [ ]:
#Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) #Set seed for reproducibility
random_1 = random_1.normal(shape = (3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape = (3, 2))
#Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###Shuffle the order of elements in a tensor

In [ ]:
#Shuffle a tensor(valuable for when you want to shuffle your data so the inherent order does not effect learning)
not_shuffled = tf.constant([[10, 7],
               [3, 4],
               [2, 5]])

#Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
#Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

#Exercise: shuffle
Read this : https://www.tensorflow.org/api_docs/python/tf/random/set_seed

It looks like if we want our shuffled tensors to be in the same order, we have got to use global level random seed as well as the operation level random seed:
##Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

##1

In [ ]:
not_shuffled = tf.constant([[100, 70],
               [30, 40],
               [20, 50]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 30,  40],
       [ 20,  50],
       [100,  70]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) #Global level random seed
tf.random.shuffle(not_shuffled, seed = 42) #operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40],
       [ 20,  50]], dtype=int32)>

##2

In [ ]:
not_shuffled = tf.constant([[110, 17],
               [13, 14],
               [12, 15]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 13,  14],
       [ 12,  15],
       [110,  17]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[110,  17],
       [ 13,  14],
       [ 12,  15]], dtype=int32)>

##3

In [ ]:
not_shuffled = tf.constant([[210, 27],
               [23, 24],
               [22, 25]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 23,  24],
       [ 22,  25],
       [210,  27]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[210,  27],
       [ 23,  24],
       [ 22,  25]], dtype=int32)>

###Other ways to make tensors


In [ ]:
#Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#Create a tensor of all zeros
tf.zeros(shape = (3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

###Tuen NumPy arrays into tensors

The main defferent between NumPy array and TensorFlow tensors is that tensors can be run on GPU(much faster for numerical computing)

In [ ]:
#You can also turn NumPy arrays into tensor
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32) #create a NumPy array between 1 to 25
numpy_A
# x = tf.constant(some_matrix) #capital for matrix or tensor
# y = tf.constant(vector) #non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape = (2, 3, 4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

###Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size  

In [ ]:
#Create a rank4 tensor(4 dimensions)
rank_4_tensor = tf.zeros(shape = [2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#Get various attributes of our tensor
print("Datatype of every elements: ", rank_4_tensor.dtype)
print("Number of dimension: ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axies: ", rank_4_tensor.shape[0])
print("Elements along the last axies: ", rank_4_tensor.shape[-1])
print("Total number of elements on our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements on our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every elements:  <dtype: 'float32'>
Number of dimension:  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axies:  2
Elements along the last axies:  5
Total number of elements on our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements on our tensor:  120


###Indexing tensors

Tensors can be indexed just like Python lists.

In [ ]:
some_list = [1, 2, 3, 4, 5]
some_list[:2]

[1, 2]

In [ ]:
#Get the first 2 elements of each dimision
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
some_list[:1]

[1]

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
#Get the first element from each dimension from each index expect for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#Create a rank 2 tensor(2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
some_list, some_list[-1]

([1, 2, 3, 4, 5], 5)

In [ ]:
#Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
#Adding extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # same as rank_2_tensor[:, :, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) #"-1" neams expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis = 0) # expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

###Manipilating tensors(tensor operations)

**Basic operation**

`+`,`-`,`*`,`/`

In [ ]:
#You can add value to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#Multiplication also work
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
#Substraction if you want
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
#We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operation.

There are two rulersour tensors(or matrices) need to fulfil if we are going to matrix multiply them.

1. The inner dimensions must match
2. The resulting matrix has the shape of the inner dimensions


In [ ]:
#Matrix mutiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
#Create a tensor(3, 2) tensor
X = tf.constant([[1, 2],
          [3, 4],
          [5, 6]])
#Create another (3, 2) tensor
Y = tf.constant([[7, 8],
          [9, 10],
          [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
#Try to matrix multiply tensors of same shape
tf.matmul(X, Y)

InvalidArgumentError: ignored

In [ ]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
#Let's change the shape of Y
tf.reshape(Y, shape = (2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
X.shape, tf.reshape(Y, shape = (2, 3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
#Try to multiply X by reshape Y
X @ tf.reshape(Y, shape = (2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y, shape = (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.reshape(X, shape = (2, 3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [ ]:
#Try change the shape of X instead Y
tf.matmul(tf.reshape(X, shape = (2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
#Can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape = (2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
#Try matrix multiplication with transpose rather than resahpe
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

📖**Resource**: Info and example of matrix multiplication: https://mathsisfun.com/algebra/matrix-multiplying.html

**The dot product**

Matrix multiplication is also referrred to as the dot product

You can perform matrix multiplication using:

*`tf.matmul()`*

*`tf.tensordot()`*

*`@`*

In [ ]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
#Perform the dot product on X and Y(requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
#Perform matrix multiplication between X and Y(transpose)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
#Perform matrix multiplication between X and Y(reshape)
tf.matmul(X, tf.reshape(Y, shape = (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
#Check the value of Y, reshape Y, and transposed Y
print("Normal Y:")
print(Y, "\n") #"\n" is for newline

print("Y reshape to (2, 3):")
print(tf.reshape(Y, shape = (2, 3)), "\n")

print("Y transposed :")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshape to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed :
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing matrix multiplication on two tensors and one of the axes does not line up, you will transpose(rather than reshape) one of the tensors to get satisify the matrix multiplication rules.

###Changing the datatype of a tensor

In [ ]:
tf.__version__

'2.14.0'

In [ ]:
#Create a new tensor with default datatype(float32)
B = tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [ ]:
C = tf.constant([7, 10])
C, C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 tf.int32)

In [ ]:
#Change from float32 to float 16(reduced precision)
B = tf.cast(B, dtype = tf.float16)
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
#Change from int32 to float32
E = tf.cast(C, dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [ ]:
E_float16 = tf.cast(E, dtype = tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

###Aggregating tensors

Aggregating tensor = condensing them from multiple values down to a smaller amount of values.

In [ ]:
#Getting the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
#Getting absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
#Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([78, 95, 47, 19, 71, 65, 23,  5, 58,  3, 50, 40, 99, 60, 40, 80, 35,
       48,  1, 47, 35, 10, 88,  4, 72,  5, 82, 93,  8, 43, 97, 97, 72, 93,
       34,  5, 28, 61, 22, 22, 25, 17, 61, 90,  3, 96,  2, 41, 49, 81])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
#Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
#Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
#Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
#Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2400>

**Exercise:** With what we learned, find the variance and standard deviation of our `E` Tensor using TensorFlow methods.

In [ ]:
#Find the variance using tf.math
tf.math.reduce_variance(tf.cast(E, dtype = tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=1008.08>

In [ ]:
#Find the variance using tfp
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1008>

In [ ]:
#Find the standard deviation, using tf.math
tf.math.reduce_std(tf.cast(E, dtype = tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=31.750275589355127>

###Find the positional maximum and minimum



In [ ]:
#Create a new tensor for finding position minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Find the max value in F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Check for equality
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [ ]:
#Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
#Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

###Squeexing a tensor(removeing alll single dimensions)

In [ ]:
#Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

###One-hot encoding tensors

In [ ]:
#Create a list of indices
some_list = [0, 1, 2, 3] #Red, Green, Blue, Purple

#one hot encode our list of indices
tf.one_hot(some_list, depth  = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Specify, custom values for one hot encoding
tf.one_hot(some_list, depth  = 4, on_value = "I am Jacob", off_value = "I am chingyen")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I am Jacob', b'I am chingyen', b'I am chingyen',
        b'I am chingyen'],
       [b'I am chingyen', b'I am Jacob', b'I am chingyen',
        b'I am chingyen'],
       [b'I am chingyen', b'I am chingyen', b'I am Jacob',
        b'I am chingyen'],
       [b'I am chingyen', b'I am chingyen', b'I am chingyen',
        b'I am Jacob']], dtype=object)>

###Squaring, log, square root

In [ ]:
#Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#Find the square root(will error, method requires non-int type)
tf.sqrt(H)

InvalidArgumentError: ignored

In [ ]:
#Find the square root
tf.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
#Find the log(will error, method requires non-int type)
tf.math.log(H)

InvalidArgumentError: ignored

In [ ]:
#Find the log
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

###Tensors and Numpy

TensorFlow interacts beatifully with NumPy arrays.

🔑**Note**:One of the main differents between a TensorFlow tensor and NumPy array is that a TensorFlow tensor can be run on a GPU and TPU(for faster numerical processing)

In [ ]:
#Create a tensor directly from NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#Convert our tensor back to a Numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#Convert tensor J to a Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
#check the datatype of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

###Finding access to GPUs

In [5]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon Nov 20 06:15:40 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

> 🔑 **Note**:If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.

🛠 Exercises
1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape
`[1, 224, 224, 3]` then squeeze it to change the shape to
`[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.



In [8]:
#1.
scalar = tf.constant(1)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2, 3],
           [4, 5, 6]])
tensor = tf.constant([[[1, 2, 3],
            [4, 5, 6]],
            [[7, 8, 9] ,
            [10, 11, 12]],
            [[13, 14, 15],
            [16, 17, 18]]])
scalar, vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]], dtype=int32)>)

In [12]:
#2-1.
scalar.shape, scalar.ndim

(TensorShape([]), 0)

In [13]:
#2-2
vector.shape, vector.ndim

(TensorShape([3]), 1)

In [14]:
#2-3
matrix.shape, matrix.ndim

(TensorShape([2, 3]), 2)

In [15]:
#2-4
tensor.shape, tensor.ndim

(TensorShape([3, 2, 3]), 3)

In [17]:
#3
third_problem_1 = tf.random.uniform(shape = [5, 300], minval = 0, maxval = 1)
third_problem_2 = tf.random.uniform(shape = [5, 300], minval = 0, maxval = 1)
third_problem_1, third_problem_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7493869 , 0.58840287, 0.8099122 , ..., 0.7712586 , 0.23590088,
         0.7411531 ],
        [0.14635837, 0.71005416, 0.4688475 , ..., 0.07975125, 0.2723235 ,
         0.36965823],
        [0.5923072 , 0.5624583 , 0.628826  , ..., 0.6274657 , 0.39211798,
         0.8473908 ],
        [0.5314356 , 0.1010294 , 0.7751082 , ..., 0.7160957 , 0.25033677,
         0.6312988 ],
        [0.2643906 , 0.10601711, 0.34025335, ..., 0.25758505, 0.5264455 ,
         0.732031  ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.31162274, 0.23213732, 0.47844005, ..., 0.89593756, 0.42961025,
         0.7742981 ],
        [0.94997585, 0.9298817 , 0.5676379 , ..., 0.5679318 , 0.6486814 ,
         0.01560962],
        [0.9095038 , 0.82903063, 0.8030901 , ..., 0.8777596 , 0.28905272,
         0.20569837],
        [0.80116427, 0.62618244, 0.11697114, ..., 0.92747104, 0.894585  ,
         0.20777595],
        [0.60534

In [19]:
#4
tf.matmul(third_problem_1, tf.transpose(third_problem_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[73.18766 , 78.189316, 76.297585, 78.44915 , 80.66689 ],
       [65.50016 , 69.833336, 71.57312 , 71.365295, 74.249245],
       [74.981674, 78.5088  , 76.95155 , 78.798836, 78.96065 ],
       [69.33763 , 75.151245, 72.279884, 72.07459 , 72.12755 ],
       [67.82036 , 73.93964 , 75.84685 , 73.34274 , 75.259865]],
      dtype=float32)>

In [20]:
#5
tf.tensordot(third_problem_1, tf.transpose(third_problem_2), axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[73.18766 , 78.189316, 76.297585, 78.44915 , 80.66689 ],
       [65.50016 , 69.833336, 71.57312 , 71.365295, 74.249245],
       [74.981674, 78.5088  , 76.95155 , 78.798836, 78.96065 ],
       [69.33763 , 75.151245, 72.279884, 72.07459 , 72.12755 ],
       [67.82036 , 73.93964 , 75.84685 , 73.34274 , 75.259865]],
      dtype=float32)>

In [21]:
#6
sixth_problem = tf.random.uniform(shape = [224, 224, 3], minval = 0, maxval = 1)
sixth_problem

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.13599086, 0.66076386, 0.58990383],
        [0.8390347 , 0.56805086, 0.6501373 ],
        [0.4036647 , 0.3241186 , 0.5824404 ],
        ...,
        [0.20306766, 0.90648353, 0.59319425],
        [0.8460858 , 0.38459718, 0.8702344 ],
        [0.37310648, 0.06655812, 0.99063027]],

       [[0.04857755, 0.5775342 , 0.44259167],
        [0.33874464, 0.44141757, 0.95702565],
        [0.86452067, 0.8125105 , 0.12586212],
        ...,
        [0.27167153, 0.30114436, 0.10309327],
        [0.88579535, 0.58560157, 0.6469077 ],
        [0.5004592 , 0.09695983, 0.22821891]],

       [[0.3773793 , 0.41380262, 0.6196796 ],
        [0.64355385, 0.95070755, 0.7491027 ],
        [0.72491443, 0.42340755, 0.8432654 ],
        ...,
        [0.3003595 , 0.06366754, 0.94345546],
        [0.15672994, 0.42656183, 0.03751266],
        [0.9730692 , 0.3105607 , 0.95238423]],

       ...,

       [[0.7307427 , 0.1555202 , 0.21066427],
        [0.06

In [22]:
#7
min_val = tf.reduce_min(sixth_problem)
max_val = tf.reduce_max(sixth_problem)
min_val, max_val

(<tf.Tensor: shape=(), dtype=float32, numpy=1.4781952e-05>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.99999475>)

In [24]:
#8
eight_problem = tf.random.uniform(shape = [1, 224, 224, 3], minval = 0, maxval = 1)
eight_squeez = tf.squeeze(eight_problem)
eight_problem, eight_problem.shape, eight_squeez, eight_squeez.shape

(<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
 array([[[[0.60881925, 0.46503413, 0.77539015],
          [0.38885152, 0.8315593 , 0.6631799 ],
          [0.6956142 , 0.15572584, 0.73651516],
          ...,
          [0.785887  , 0.17811918, 0.89262486],
          [0.3931352 , 0.31705177, 0.6755856 ],
          [0.2655481 , 0.36935484, 0.08558691]],
 
         [[0.93873477, 0.762516  , 0.9720404 ],
          [0.1897825 , 0.61863315, 0.7801665 ],
          [0.756426  , 0.34614825, 0.28495455],
          ...,
          [0.7090405 , 0.89059865, 0.13007331],
          [0.25696087, 0.8807653 , 0.44161606],
          [0.14558256, 0.1189009 , 0.6411755 ]],
 
         [[0.9027206 , 0.50270593, 0.53844   ],
          [0.0880177 , 0.9686513 , 0.64109886],
          [0.45702446, 0.68171096, 0.8526354 ],
          ...,
          [0.4866495 , 0.00194716, 0.3278209 ],
          [0.01352251, 0.18545401, 0.07356238],
          [0.6125939 , 0.84530175, 0.8146032 ]],
 
         ...,
 
       

In [29]:
#9
tf.random.set_seed(42)
ninth_problem = tf.random.uniform(shape = [10], minval = 0, maxval = 20, dtype = tf.int32)
maxidx    = tf.argmax(ninth_problem)
ninth_problem, maxidx

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 7,  9,  1,  6, 12,  4,  3,  3, 11, 11], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int64, numpy=4>)

In [32]:
#10
tf.one_hot(ninth_problem, depth = 20)

<tf.Tensor: shape=(10, 20), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
     